### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by mdvsh** [soumitradev/Hangman#1]
# Why Not ?!

please add this in the README.
It lacks a certain feel without it.

Sincerely,
A Well Wisher

**Comment by soumitradev** [comment]
I do agree. I'll assign this to myself now.

Nice first issue, I'll start working on this right now, since it looks like a lot of work.

I'll work on this for the next week or so, report my progress for the week here, and I'll continue doing that until this is fixed.

**Comment by soumitradev** [comment]
It seems to be fixed! I don't know how such a feat was achieved, but it just happened automatically I guess!

**Comment by mdvsh** [comment]
Blessing of WhiNyut God indeed.
